[tool.poetry]
name = "oneiro"
version = "0.1.0"
description = ""
authors = ["Tom <t.p.kellett@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
